<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alias' => 'Псевдоним',
    'Create Goal' => 'Создать Цель',
    'Created At' => 'Создано',
    'Description' => 'Описание',
    'Done At' => 'Выполнено',
    'Goal' => 'Цель',
    'Goals' => 'Цели',
    'ID' => '',
    'Icon' => 'Иконка',
    'Percent' => 'Процент выполнения',
    'Priority' => 'Приоритет',
    'Smart Achievable' => 'Достижимый',
    'Smart Measurable' => 'Измеримый',
    'Smart Relevant' => 'Актуальный ',
    'Smart Specific' => 'Конкретный',
    'Smart Time Bound' => 'Ограниченный во времени',
    'Status' => 'Статус',
    'Title' => 'Название',
    'To Be Done At' => 'Выполнить к',
    'Type' => 'Тип',
    'Updated At' => 'Обновлено',
    'Write' => 'Напиать',
    'Write new message' => 'Написать новое сообщение',
];
