<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => '',
    'Task' => 'Задача',
    'Add task "{0}"' => 'Добавлена задача "{0}"',
    'Close' => 'Закрыть',
    'Close task "{0}"' => 'Выполнена задача "{0}"',
    'Closed' => 'Выполнено',
    'Closed At' => 'Закрыто',
    'Create Task' => 'Создать Задачу',
    'Created At' => 'Создано',
    'Date' => 'Выполнить к',
    'Goal ID' => 'ID Цели',
    'Open' => 'Открыть',
    'Opened' => 'Открыто',
    'Percent' => 'Процент выполнения',
    'Tasks' => 'Задачи',
    'Title' => 'Название',
];
