<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'achievable_hint' => 'The third criterion stresses the importance of goals that are realistic and also attainable. Whilst an attainable goal may stretch a team in order to achieve it, the goal is not extreme. That is, the goals are neither out of reach nor below standard performance, since these may be considered meaningless. When you identify goals that are most important to you, you begin to figure out ways you can make them come true. You develop the attitudes, abilities, skills and financial capacity to reach them. The theory states that an attainable goal may cause goal-setters to identify previously overlooked opportunities to bring themselves closer to the achievement of their goals.

An achievable goal will usually answer the question How?

    * How can the goal be accomplished?
    * How realistic is the goal based on other constraints?
',
    'measurable_hint' => 'The second criterion stresses the need for concrete criteria for measuring progress toward the attainment of the goal. The thought behind this is that if a goal is not measurable it is not possible to know whether a team is making progress toward successful completion. Measuring progress is supposed to help a team stay on track, reach its target dates and experience the exhilaration of achievement that spurs it on to continued effort required to reach the ultimate goal.

Indicators should be quantifiable. A measurable goal will usually answer questions such as:

    * How much?
    * How many?
    * How will I know when it is accomplished?
',
    'relevant_hint' => 'The fourth criterion stresses the importance of choosing goals that matter. A bank manager\'s goal to "Make 50 peanut butter and jelly sandwiches by 3pm" may be specific, measurable, attainable and time-bound but lacks relevance. Many times you will need support to accomplish a goal: resources, a champion voice, someone to knock down obstacles. Goals that are relevant to your boss, your team, your organization will receive that needed support.

Relevant goals (when met) drive the team, department and organization forward. A goal that supports or is in alignment with other goals would be considered a relevant goal.

A relevant goal can answer yes to these questions:

    * Does this seem worthwhile?
    * Is this the right time?
    * Does this match our other efforts/needs?
    * Are you the right person?
    * Is it applicable in the current socio-economic environment?
',
    'specific_hint' => 'The criterion stresses the need for a specific goal rather than a more general one. This means the goal is clear and unambiguous; without vagaries and platitudes. To make goals specific, they must tell a team exactly what\'s expected, why it\'s important, who’s involved, where it\'s going to happen and which attributes are important.

A specific goal will usually answer the five \'W\' questions:

    * What: What do I want to accomplish?
    * Why: Specific reasons, purpose or benefits of accomplishing the goal.
    * Who: Who is involved?
    * Where: Identify a location.
    * Which: Identify requirements and constraints.
',
    'time_bound_hint' => 'The fifth criterion stresses the importance of grounding goals within a time-frame, giving them a target date. A commitment to a deadline helps a team focus their efforts on completion of the goal on or before the due date. This part of the SMART goal criteria is intended to prevent goals from being overtaken by the day-to-day crises that invariably arise in an organization. A time-bound goal is intended to establish a sense of urgency.

A time-bound goal will usually answer the questions:

    * When?
    * What can I do six months from now?
    * What can I do six weeks from now?
    * What can I do today?
',
];
